[package]
name = "fyrox"
version = "0.28.0"
authors = ["Dmitry Stepanov <d1maxa@yandex.ru>"]
edition = "2021"
license = "MIT"
description = "2D/3D Game Engine"
keywords = ["sound", "game", "engine", "3d", "gui"]
categories = ["game-engines", "graphics", "gui", "rendering", "wasm"]
include = ["/src/**/*", "/Cargo.toml", "/LICENSE", "/README.md"]
homepage = "https://fyrox.rs"
documentation = "https://docs.rs/fyrox"
repository = "https://github.com/FyroxEngine/Fyrox"
readme = "README.md"
resolver = "2"
rust-version = "1.56"

[workspace]
members = [
    "fyrox-core-derive",
    "fyrox-core",
    "fyrox-sound",
    "fyrox-ui",
    "fyrox-resource",
    "examples/wasm",
	"editor",
    "editor-standalone",
	"template"
]
exclude = ["examples/scripting"]

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
debug = true

[dependencies]
fyrox-core-derive = { path = "fyrox-core-derive", version = "0.17.0" }
fyrox-core = { path = "fyrox-core", version = "0.22.0", features = ["serde"] }
fyrox-sound = { path = "fyrox-sound", version = "0.29.0" }
fyrox-ui = { path = "fyrox-ui", version = "0.19.0" }
fyrox-resource = { path = "fyrox-resource", version = "0.6.0" }
rapier2d = { version = "0.16", features = ["debug-render"] }
rapier3d = { version = "0.16", features = ["debug-render"] }
image = { version = "0.24.3", default-features = false, features = ["gif", "jpeg", "png", "tga", "tiff", "bmp"] }
inflate = "0.4.5"
serde = { version = "1", features = ["derive"] }
lazy_static = "1.4.0"
ddsfile = "0.5.0"
rayon = "1.5.1"
tbc = "0.3.0"
bitflags = "1.3.2"
glow = "0.11"
walkdir = "2.3.2"
ron = "0.8.0"
fxhash = "0.2.1"
strum = "0.24.0"
strum_macros = "0.24.0"
notify = "5"
clap = { version = "4", features = ["derive"] }

[features]
enable_profiler = ["fyrox-core/enable_profiler"]

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
glutin = {version = "0.29.0", features = ["serde"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
winit = { version = "0.27.1", features = ["serde"] }
